"""Pace: the campus wayfinding system, as in-world signage on the 16 px grid.

Pace has no body, no face and no portrait (design/characters/pace.md). It is a
rounded wayfinding icon plus orderly horizontal bars, drawn as environment
pieces: wall signs, a hanging sign, floor inlays and a standing directory.

Pixels as code: the two icons are hand-placed key grids; every other piece is a
drawing function over the palette keys below. PNG/JSON outputs are generated by
build_pace.py and never hand-edited. Light comes from the upper left, hard
pixels only.

Palette: ink, warm stone, blue glass and brass from STYLE_BIBLE section 3.
Never the violet ramp, never a UI marker hex (#19AFA2 #EC776D #9876D5 #E6B750).
Brass appears as small trim only; its lightest step (#F5D580) is reserved for
glints and is not used at all at present.
"""
import numpy as np

PAL = {
    "o": "#202337", "k": "#343650", "t": "#535971", "a": "#777A8C",   # ink
    "D": "#665D65", "d": "#968A85", "s": "#C7B7A0", "S": "#F0DEC0",   # warm stone
    "F": "#203A50", "f": "#366479", "g": "#5AA3AE", "h": "#A0DDD4",   # blue glass
    "p": "#705056", "b": "#AC7655", "B": "#E1AC62", "y": "#F5D580",   # brass
}
MARKERS = {"#19AFA2", "#EC776D", "#9876D5", "#E6B750"}
VIOLET = {"#413755", "#67547C", "#9477AF", "#C3A6D6"}
# Glint budgets per piece (pixels): lightest brass and lightest glass.
GLINT_LIMITS = {"y": 3, "h": 4}
FLOOR = "#F0DEC0"   # STONE[3], the review-room floor
WALL = "#968A85"    # STONE[1], the review-room wall face


def rgb(k):
    h = PAL[k]
    return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5))


# ------------------------------------------------------------------ canvas helpers

def new(w, h):
    return np.zeros((h, w, 4), np.uint8)


def put(a, x, y, k):
    if 0 <= y < a.shape[0] and 0 <= x < a.shape[1]:
        a[y, x] = (*rgb(k), 255)


def clear(a, x, y):
    a[y, x] = 0


def rect(a, x0, y0, x1, y1, k):
    for y in range(y0, y1):
        for x in range(x0, x1):
            put(a, x, y, k)


def grid(a, rows, x0, y0, remap=None):
    """Blit a key grid; '.' is transparent. remap swaps keys (state variants)."""
    for dy, row in enumerate(rows):
        for dx, ch in enumerate(row):
            if ch != ".":
                put(a, x0 + dx, y0 + dy, (remap or {}).get(ch, ch))


def cast(a, x0, x1, y):
    """Two-row contact shadow below a base, like environment.Room.cast."""
    for x in range(x0 + 1, x1 + 1):
        put(a, x, y, "t")
    for x in range(x0 + 2, x1 + 2):
        put(a, x, y + 1, "a")


# ------------------------------------------------------------------ the icon

# Rounded badge, no face: a stone ring round a blue-glass screen that carries
# three horizontal bars and a route chevron. Ring: lit top-left, shaded
# bottom-right; the screen has one lit row and a dark recess row.
ICON16 = [
    "..oooooooooooo..",
    ".oSSSSSSSSSSsso.",
    "oSggggggggffffdo",
    "oSffffffffffffdo",
    "oSfSSSSSSfffffdo",
    "oSfSSSSSSfSfffdo",
    "oSfffffffffSffdo",
    "oSfSSSSSffffSfdo",
    "oSfSSSSSfffSffdo",
    "oSffffffffSfffdo",
    "oSfSSSSSSSffffdo",
    "oSfSSSSSSSffffdo",
    "oSffffffffffffdo",
    "oSFFFFFFFFFFFFdo",
    ".oddddddddddddo.",
    "..oooooooooooo..",
]

# 8x8 variant for use inside signs: the same bars without the chevron.
ICON8 = [
    ".oooooo.",
    "ofSSSSfo",
    "offffffo",
    "ofSSSffo",
    "offffffo",
    "ofSSSSfo",
    "oFFFFFFo",
    ".oooooo.",
]

# Optional-guidance state (epilogue): the icon goes quiet, ink on stone.
QUIET = {"f": "s", "F": "d", "S": "k", "g": "S"}


def icon16():
    a = new(16, 16)
    grid(a, ICON16, 0, 0)
    return a


def icon8(state="default"):
    a = new(8, 8)
    grid(a, ICON8, 0, 0, QUIET if state == "optional" else None)
    return a


# ------------------------------------------------------------------ sign faces

FACE = {  # face, lit top row, recess row, bar
    "default": ("f", "g", "F", "S"),
    "repeat": ("f", "g", "F", "S"),
    "optional": ("s", "S", "d", "k"),
}
BAR_LENGTHS = {"default": (15, 11, 13), "repeat": (13, 13, 13), "optional": (15, 11, 13)}


def framed(a, x0, y0, x1, y1):
    """Rounded ink frame with a lit top-left and brass screws (x1, y1 exclusive)."""
    rect(a, x0, y0, x1, y1, "o")
    rect(a, x0 + 1, y0 + 1, x1 - 1, y1 - 1, "k")
    rect(a, x0 + 1, y0 + 1, x1 - 1, y0 + 2, "t")
    rect(a, x0 + 1, y0 + 1, x0 + 2, y1 - 1, "t")
    for x, y in ((x0, y0), (x1 - 1, y0), (x0, y1 - 1), (x1 - 1, y1 - 1)):
        clear(a, x, y)
    for x, y in ((x0 + 1, y0 + 1), (x1 - 2, y0 + 1), (x0 + 1, y1 - 2), (x1 - 2, y1 - 2)):
        put(a, x, y, "b")


def face(a, x0, y0, x1, y1, state):
    f, top, bot, _ = FACE[state]
    rect(a, x0, y0, x1, y1, f)
    rect(a, x0, y0, x1, y0 + 1, top)
    rect(a, x0, y1 - 1, x1, y1, bot)


def wall_sign_2x1(state="default"):
    """32x16: badge icon and three orderly bars on a lit face; wall layer.
    Rows 0-13 are the panel, rows 14-15 its cast shadow on the wall."""
    a = new(32, 16)
    framed(a, 0, 0, 32, 14)
    face(a, 2, 2, 30, 12, state)
    blit(a, icon8(state), 3, 3)
    bar = FACE[state][3]
    for (y, n) in zip((3, 6, 9), BAR_LENGTHS[state]):
        rect(a, 13, y, 13 + n, y + 2, bar)
    cast(a, 0, 31, 14)
    return a


def wall_logo_1x1():
    """16x16: the 8x8 icon alone on a small plate; wall layer."""
    a = new(16, 16)
    framed(a, 0, 0, 16, 14)
    face(a, 2, 2, 14, 12, "default")
    blit(a, icon8(), 4, 3)
    cast(a, 0, 15, 14)
    return a


def hanging_sign():
    """16x24: wall rail, two brass chains, the 16x16 icon as the plate, cast on the wall."""
    a = new(16, 24)
    rect(a, 2, 0, 14, 1, "o")
    rect(a, 2, 1, 14, 2, "k")
    for i, y in enumerate(range(2, 6)):
        for x in (3, 12):
            put(a, x, y, "b" if i % 2 == 0 else "p")
    blit(a, icon16(), 0, 6)
    cast(a, 0, 15, 22)
    return a


def blit(a, src, x0, y0):
    h, w = src.shape[:2]
    m = src[:, :, 3] > 0
    a[y0:y0 + h, x0:x0 + w][m] = src[m]


# ------------------------------------------------------------------ floor inlays
# Same language as the garden ring's corner squares and the RECORDS mat: a bevelled
# slab let into the floor, dark inlaid glyph, a shaft-and-head arrow. Quieter than
# the mat: stone and blue glass, no brass fill.

def slab(a, x0, y0, x1, y1):
    rect(a, x0, y0, x1, y1, "D")
    rect(a, x0 + 1, y0 + 1, x1 - 1, y1 - 1, "s")
    rect(a, x0 + 1, y0 + 1, x1 - 1, y0 + 2, "S")
    rect(a, x0 + 1, y0 + 1, x0 + 2, y1 - 1, "S")
    rect(a, x0 + 1, y1 - 2, x1 - 1, y1 - 1, "d")
    rect(a, x1 - 2, y0 + 1, x1 - 1, y1 - 1, "d")
    for x, y in ((x0, y0), (x1 - 1, y0), (x0, y1 - 1), (x1 - 1, y1 - 1)):
        clear(a, x, y)


def inlay(a, mask, x0, y0):
    """Inlaid glass glyph: body in the mid glass step, lower-right edge in the dark step."""
    h, w = mask.shape
    for y in range(h):
        for x in range(w):
            if mask[y, x]:
                edge = not (x + 1 < w and mask[y, x + 1]) or not (y + 1 < h and mask[y + 1, x])
                put(a, x0 + x, y0 + y, "F" if edge else "f")


def chevron_mask(direction):
    m = np.zeros((8, 5), bool)  # east
    for i in range(4):
        m[i, i:i + 2] = True
        m[7 - i, i:i + 2] = True
    return np.rot90(m, {"e": 0, "n": 1, "w": 2, "s": 3}[direction])


def floor_chevron(direction="e"):
    """16x16 floor tile: a 12x12 slab inlay with one route chevron."""
    a = new(16, 16)
    slab(a, 2, 2, 14, 14)
    m = chevron_mask(direction)
    h, w = m.shape
    inlay(a, m, 2 + (12 - w) // 2, 2 + (12 - h) // 2)
    return a


def floor_arrow_plate(direction="e"):
    """32x16 (E/W) or 16x32 (N/S): slab with the 8x8 icon at the tail and a shaft-and-head arrow."""
    e = np.zeros((16, 32), bool)
    e[7:9, 14:24] = True                                   # shaft, 2 px like the mat's
    for i, (y0, y1) in enumerate(((4, 12), (5, 11), (6, 10), (7, 9))):
        e[y0:y1, 24 + i] = True                            # head, 4 columns
    m = np.fliplr(e) if direction == "w" else np.rot90(e, {"n": 1, "s": 3}.get(direction, 0))
    h, w = m.shape
    a = new(w, h)
    slab(a, 1, 1, w - 1, h - 1)
    inlay(a, m, 0, 0)
    ix, iy = {"e": (4, 4), "w": (20, 4), "n": (4, 20), "s": (4, 4)}[direction]
    blit(a, icon8(), ix, iy)
    return a


# ------------------------------------------------------------------ standing directory

def directory(state="default"):
    """32x32 standing directory: board on two legs. Sprite covers 2x2 cells; the ground
    footprint is the bottom row (2x1 cells). Rear-prop layer, shadow baked."""
    a = new(32, 32)
    cast(a, 3, 29, 30)
    for x0 in (5, 23):  # legs and feet
        rect(a, x0, 25, x0 + 4, 28, "o")
        rect(a, x0 + 1, 25, x0 + 2, 28, "t")
        rect(a, x0 + 2, 25, x0 + 3, 28, "k")
        rect(a, x0 - 1, 28, x0 + 5, 30, "o")
        rect(a, x0, 28, x0 + 4, 29, "t")
    rect(a, 1, 0, 31, 25, "o")
    rect(a, 2, 1, 30, 24, "k")
    rect(a, 2, 1, 30, 2, "a")        # lit top edge
    rect(a, 2, 2, 30, 3, "t")
    rect(a, 2, 1, 3, 24, "t")
    for x, y in ((1, 0), (30, 0), (1, 24), (30, 24)):
        clear(a, x, y)
    f, top, bot, bar = FACE[state]
    rect(a, 3, 3, 29, 23, f)
    rect(a, 3, 3, 29, 4, top)
    rect(a, 3, 22, 29, 23, bot)
    blit(a, icon8(state), 4, 4)
    rect(a, 14, 5, 27, 7, bar)       # title bar
    rect(a, 14, 9, 23, 10, "d" if state != "optional" else "t")  # sub line
    rect(a, 4, 12, 28, 13, bot if state != "optional" else "d")  # divider
    lens = {"default": (14, 10, 12), "repeat": (12, 12, 12), "optional": (14, 10, 12)}[state]
    for y, n in zip((14, 17, 20), lens):
        rect(a, 5, y, 7, y + 2, "b")
        put(a, 5, y, "B")
        rect(a, 9, y, 9 + n, y + 2, bar)
    return a


# ------------------------------------------------------------------ registry
# name -> dict(build, layer, footprint cells, origin_px (footprint top-left in the sprite),
# collision (blocked footprint cells), bg for the sheet, note)

def piece(build, layer, fp, bg, note, origin=(0, 0), collision=(), state=None):
    return dict(build=build, layer=layer, footprint=fp, origin=origin, collision=list(collision),
                bg=bg, note=note, state=state)


PIECES = {
    "pace_icon_16": piece(icon16, "rear_wall", (1, 1), "wall", "The Pace icon: a rounded badge, three bars and a route chevron. No face."),
    "pace_icon_8": piece(icon8, "rear_wall", (1, 1), "wall", "8x8 small variant for inside signs, not placed alone."),
    "pace_logo_plate_1x1": piece(wall_logo_1x1, "rear_wall", (1, 1), "wall", "Icon on a small wall plate with cast shadow."),
    "pace_wall_sign_2x1": piece(wall_sign_2x1, "rear_wall", (2, 1), "wall", "Wall sign: icon and three bars.", state="default"),
    "pace_wall_sign_2x1_repeat": piece(lambda: wall_sign_2x1("repeat"), "rear_wall", (2, 1), "wall",
                                       "Errors accumulating: the three bars repeat at one length.", state="repeat"),
    "pace_wall_sign_2x1_optional": piece(lambda: wall_sign_2x1("optional"), "rear_wall", (2, 1), "wall",
                                         "Epilogue: unlit stone plaque, ink bars, optional guidance.", state="optional"),
    "pace_hanging_sign": piece(hanging_sign, "rear_wall", (1, 2), "wall", "Brass chains from a wall rail; the 16x16 icon is the plate."),
    "pace_floor_chevron_e": piece(lambda: floor_chevron("e"), "floor_marking", (1, 1), "floor", "Route chevron slab, east."),
    "pace_floor_chevron_n": piece(lambda: floor_chevron("n"), "floor_marking", (1, 1), "floor", "Route chevron slab, north."),
    "pace_floor_chevron_w": piece(lambda: floor_chevron("w"), "floor_marking", (1, 1), "floor", "Route chevron slab, west."),
    "pace_floor_chevron_s": piece(lambda: floor_chevron("s"), "floor_marking", (1, 1), "floor", "Route chevron slab, south."),
    "pace_floor_arrow_e": piece(lambda: floor_arrow_plate("e"), "floor_marking", (2, 1), "floor", "Arrow plate with icon, east."),
    "pace_floor_arrow_w": piece(lambda: floor_arrow_plate("w"), "floor_marking", (2, 1), "floor", "Arrow plate with icon, west."),
    "pace_floor_arrow_n": piece(lambda: floor_arrow_plate("n"), "floor_marking", (1, 2), "floor", "Arrow plate with icon, north."),
    "pace_floor_arrow_s": piece(lambda: floor_arrow_plate("s"), "floor_marking", (1, 2), "floor", "Arrow plate with icon, south."),
    "pace_directory": piece(directory, "rear_prop", (2, 1), "floor", "Standing directory board on two legs.",
                            origin=(0, 16), collision=[(0, 0), (1, 0)], state="default"),
    "pace_directory_repeat": piece(lambda: directory("repeat"), "rear_prop", (2, 1), "floor",
                                   "Errors accumulating: every entry repeats at one length.",
                                   origin=(0, 16), collision=[(0, 0), (1, 0)], state="repeat"),
    "pace_directory_optional": piece(lambda: directory("optional"), "rear_prop", (2, 1), "floor",
                                     "Epilogue: unlit stone board, optional guidance.",
                                     origin=(0, 16), collision=[(0, 0), (1, 0)], state="optional"),
}


def build_all():
    return {name: p["build"]() for name, p in PIECES.items()}
